import os
import datetime
import re

def post_process():
    # 从环境变量获取配置，默认值为硬编码值
    input_file = os.getenv("POST_PROCESS_INPUT_FILE", "refined_draft.md")
    output_file = os.getenv("POST_PROCESS_OUTPUT_FILE", "final_polished_output.md")
    
    if not os.path.exists(input_file):
        print("Error: Draft file missing.")
        return
        
    with open(input_file, "r", encoding="utf-8") as f:
        content = f.read()
        
    # 简单的路径检查 - 修复正则表达式转义问题
    # 使用原始字符串，不包含多余的引号
    images = re.findall(r'!\[.*?]\]\((.*?)\)', content)
    
    for img_path in images:
        if not os.path.exists(img_path):
            print(f"Warning: Referenced image not found: {img_path}")
        else:
            print(f"[OK] Image verified: {img_path}")
            
    # 添加元数据页脚
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    footer = f"\n\n---\n*文档生成时间: {timestamp} | Generated by Gemini Conductor Workflow*"
    
    final_content = content + footer
    
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(final_content)
        
    print(f"[+] 最终交付物已生成: {output_file}")

if __name__ == "__main__":
    post_process()